"""Build the Salt SDK Field Guide.

    python3 tools/field-guide/build.py                       # writes docs/field-guide/index.html
    python3 tools/field-guide/build.py --fragment page.html  # also writes the page without a document wrapper

The page is template.html with the three terminal recordings inlined. Each recording is a set
of line-diff frames (recordings/<name>.frames.json, made from the .cast by render_cast.py) plus
a poster frame chosen to show its result, so the page reads fully before anything plays.
"""
import argparse
import html
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
RECORDINGS = os.path.join(HERE, "recordings")
TAG = re.compile(r"<[^>]+>")

# Poster: the last frame whose screen shows `want` and not `avoid` (None means the final frame).
POSTERS = {
    "nara-create-org": ("Wrote robo-setup-nara-capital", "Goodbye"),
    "nara-ssh-setup": (None, None),
    "nara-activate": ("2FA activation: complete", "Goodbye"),
}

# A plain web host needs the document wrapper itself; hosts that add their own take --fragment.
STANDALONE_HEAD = """<!doctype html>
<!-- Generated by tools/field-guide/build.py from tools/field-guide/template.html. Edit those and rebuild. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta property="og:type" content="article">
<meta property="og:title" content="Salt SDK Field Guide">
<meta property="og:description" content="Technical onboarding for teams evaluating Salt: salt-fi, signing in with your wallet, Robo Guardians installed by Claude Code over SSH, and the policy layer.">
<meta property="og:url" content="https://salt-space.github.io/salt-fi/field-guide/">
<link rel="canonical" href="https://salt-space.github.io/salt-fi/field-guide/">
"""


def fmt(seconds):
    s = max(0, round(seconds))
    return f"{s // 60}:{s % 60:02d}"


def poster_rows(data, want, avoid):
    rows = [""] * data["h"]
    chosen = None
    for _, diff in data["frames"]:
        for y, row in diff:
            rows[y] = row
        text = html.unescape(TAG.sub("", "\n".join(rows)))
        if want is None or (want in text and (avoid is None or avoid not in text)):
            chosen = list(rows)
    assert chosen is not None, f"no poster frame matched {want!r}"
    return chosen


def build_fragment():
    page = open(os.path.join(HERE, "template.html")).read()
    for name, (want, avoid) in POSTERS.items():
        data = json.load(open(os.path.join(RECORDINGS, f"{name}.frames.json")))
        poster = "".join(f'<span class="row">{r}</span>' for r in poster_rows(data, want, avoid))
        payload = json.dumps({"h": data["h"], "duration": data["duration"], "frames": data["frames"]},
                             separators=(",", ":")).replace("</", "<\\/")
        page = page.replace(f"{{{{POSTER {name}}}}}", poster)
        page = page.replace(f"{{{{DURATION {name}}}}}", fmt(data["duration"]))
        page = page.replace(f"{{{{DATA {name}}}}}", f'<script type="application/json" id="rec-{name}">{payload}</script>')
    leftover = re.findall(r"\{\{[A-Z]+ [^}]+\}\}", page)
    assert not leftover, leftover
    return page


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", default=os.path.join(REPO, "docs", "field-guide", "index.html"))
    parser.add_argument("--fragment", help="also write the page without the document wrapper")
    args = parser.parse_args()

    page = build_fragment()
    split = page.index('<div class="page">')
    standalone = STANDALONE_HEAD + page[:split] + "</head>\n<body>\n" + page[split:] + "\n</body>\n</html>\n"
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(standalone)
    print("wrote", os.path.relpath(args.out, REPO))
    if args.fragment:
        with open(args.fragment, "w") as f:
            f.write(page)
        print("wrote", args.fragment)


if __name__ == "__main__":
    main()
